/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* top =  1  *)
(* src = "pixelSensorFsm.v:32" *)
module pixelSensorFsm(clk, reset, erase, expose, read, convert);
  (* src = "pixelSensorFsm.v:102" *)
  wire [31:0] _000_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _001_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _002_;
  (* src = "pixelSensorFsm.v:102" *)
  wire [2:0] _003_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _004_;
  (* src = "pixelSensorFsm.v:102" *)
  wire [2:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _178_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _179_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _180_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _181_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _182_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _183_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _184_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _185_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _186_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _187_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _188_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _189_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _190_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _191_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _192_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _193_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _194_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _195_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _196_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _197_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _198_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _199_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _200_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _201_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _202_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _203_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _204_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _205_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _206_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _207_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _208_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _209_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _210_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _211_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _212_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _213_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _214_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _215_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _216_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _217_;
  (* src = "pixelSensorFsm.v:102" *)
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  (* src = "pixelSensorFsm.v:33" *)
  wire _226_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _227_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _228_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _229_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _230_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _231_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _232_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _233_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _234_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _235_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _236_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _237_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _238_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _239_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _240_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _241_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _242_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _243_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _244_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _245_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _246_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _247_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _248_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _249_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _250_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _251_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _252_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _253_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _254_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _255_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _256_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _257_;
  (* src = "pixelSensorFsm.v:57" *)
  wire _258_;
  (* src = "pixelSensorFsm.v:35" *)
  wire _259_;
  (* src = "pixelSensorFsm.v:36" *)
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _441_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _442_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _443_;
  (* src = "pixelSensorFsm.v:37" *)
  wire _444_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _445_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _446_;
  (* src = "pixelSensorFsm.v:56" *)
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  (* src = "pixelSensorFsm.v:33" *)
  input clk;
  (* src = "pixelSensorFsm.v:38" *)
  output convert;
  (* src = "pixelSensorFsm.v:57" *)
  wire [31:0] counter;
  (* src = "pixelSensorFsm.v:35" *)
  output erase;
  (* src = "pixelSensorFsm.v:36" *)
  output expose;
  (* src = "pixelSensorFsm.v:56" *)
  wire [2:0] next_state;
  (* src = "pixelSensorFsm.v:37" *)
  output read;
  (* src = "pixelSensorFsm.v:34" *)
  input reset;
  (* src = "pixelSensorFsm.v:56" *)
  wire [2:0] state;
  IVX1_CV _496_ (
    .A(_447_),
    .Y(_433_)
  );
  IVX1_CV _497_ (
    .A(_238_),
    .Y(_434_)
  );
  IVX1_CV _498_ (
    .A(_252_),
    .Y(_435_)
  );
  IVX1_CV _499_ (
    .A(_445_),
    .Y(_436_)
  );
  IVX1_CV _500_ (
    .A(_221_),
    .Y(_437_)
  );
  IVX1_CV _501_ (
    .A(_226_),
    .Y(_223_)
  );
  NRX1_CV _502_ (
    .A(_446_),
    .B(_445_),
    .Y(_438_)
  );
  ANX1_CV _503_ (
    .A(_447_),
    .B(_438_),
    .Y(_439_)
  );
  NDX1_CV _504_ (
    .A(_447_),
    .B(_438_),
    .Y(_440_)
  );
  NRX1_CV _505_ (
    .A(_227_),
    .B(_439_),
    .Y(_178_)
  );
  ANX1_CV _506_ (
    .A(_227_),
    .B(_434_),
    .Y(_261_)
  );
  ANX1_CV _507_ (
    .A(_227_),
    .B(_238_),
    .Y(_262_)
  );
  EOX1_CV _508_ (
    .A(_227_),
    .B(_238_),
    .Y(_263_)
  );
  ANX1_CV _509_ (
    .A(_440_),
    .B(_263_),
    .Y(_189_)
  );
  ANX1_CV _510_ (
    .A(_249_),
    .B(_262_),
    .Y(_264_)
  );
  ORX1_CV _511_ (
    .A(_249_),
    .B(_262_),
    .Y(_265_)
  );
  NDX1_CV _512_ (
    .A(_440_),
    .B(_265_),
    .Y(_266_)
  );
  NRX1_CV _513_ (
    .A(_264_),
    .B(_266_),
    .Y(_200_)
  );
  ANX1_CV _514_ (
    .A(_252_),
    .B(_264_),
    .Y(_267_)
  );
  ORX1_CV _515_ (
    .A(_252_),
    .B(_264_),
    .Y(_268_)
  );
  NDX1_CV _516_ (
    .A(_440_),
    .B(_268_),
    .Y(_269_)
  );
  NRX1_CV _517_ (
    .A(_267_),
    .B(_269_),
    .Y(_203_)
  );
  ANX1_CV _518_ (
    .A(_253_),
    .B(_267_),
    .Y(_270_)
  );
  ORX1_CV _519_ (
    .A(_253_),
    .B(_267_),
    .Y(_271_)
  );
  NDX1_CV _520_ (
    .A(_440_),
    .B(_271_),
    .Y(_272_)
  );
  NRX1_CV _521_ (
    .A(_270_),
    .B(_272_),
    .Y(_204_)
  );
  ANX1_CV _522_ (
    .A(_254_),
    .B(_270_),
    .Y(_273_)
  );
  ORX1_CV _523_ (
    .A(_254_),
    .B(_270_),
    .Y(_274_)
  );
  NDX1_CV _524_ (
    .A(_440_),
    .B(_274_),
    .Y(_275_)
  );
  NRX1_CV _525_ (
    .A(_273_),
    .B(_275_),
    .Y(_205_)
  );
  ANX1_CV _526_ (
    .A(_255_),
    .B(_273_),
    .Y(_276_)
  );
  ORX1_CV _527_ (
    .A(_255_),
    .B(_273_),
    .Y(_277_)
  );
  NDX1_CV _528_ (
    .A(_440_),
    .B(_277_),
    .Y(_278_)
  );
  NRX1_CV _529_ (
    .A(_276_),
    .B(_278_),
    .Y(_206_)
  );
  ANX1_CV _530_ (
    .A(_256_),
    .B(_276_),
    .Y(_279_)
  );
  ORX1_CV _531_ (
    .A(_256_),
    .B(_276_),
    .Y(_280_)
  );
  NDX1_CV _532_ (
    .A(_440_),
    .B(_280_),
    .Y(_281_)
  );
  NRX1_CV _533_ (
    .A(_279_),
    .B(_281_),
    .Y(_207_)
  );
  ANX1_CV _534_ (
    .A(_257_),
    .B(_279_),
    .Y(_282_)
  );
  ORX1_CV _535_ (
    .A(_257_),
    .B(_279_),
    .Y(_283_)
  );
  NDX1_CV _536_ (
    .A(_440_),
    .B(_283_),
    .Y(_284_)
  );
  NRX1_CV _537_ (
    .A(_282_),
    .B(_284_),
    .Y(_208_)
  );
  ANX1_CV _538_ (
    .A(_258_),
    .B(_282_),
    .Y(_285_)
  );
  ORX1_CV _539_ (
    .A(_258_),
    .B(_282_),
    .Y(_286_)
  );
  NDX1_CV _540_ (
    .A(_440_),
    .B(_286_),
    .Y(_287_)
  );
  NRX1_CV _541_ (
    .A(_285_),
    .B(_287_),
    .Y(_209_)
  );
  ANX1_CV _542_ (
    .A(_228_),
    .B(_285_),
    .Y(_288_)
  );
  ORX1_CV _543_ (
    .A(_228_),
    .B(_285_),
    .Y(_289_)
  );
  NDX1_CV _544_ (
    .A(_440_),
    .B(_289_),
    .Y(_290_)
  );
  NRX1_CV _545_ (
    .A(_288_),
    .B(_290_),
    .Y(_179_)
  );
  ANX1_CV _546_ (
    .A(_229_),
    .B(_288_),
    .Y(_291_)
  );
  ORX1_CV _547_ (
    .A(_229_),
    .B(_288_),
    .Y(_292_)
  );
  NDX1_CV _548_ (
    .A(_440_),
    .B(_292_),
    .Y(_293_)
  );
  NRX1_CV _549_ (
    .A(_291_),
    .B(_293_),
    .Y(_180_)
  );
  ANX1_CV _550_ (
    .A(_230_),
    .B(_291_),
    .Y(_294_)
  );
  ORX1_CV _551_ (
    .A(_230_),
    .B(_291_),
    .Y(_295_)
  );
  NDX1_CV _552_ (
    .A(_440_),
    .B(_295_),
    .Y(_296_)
  );
  NRX1_CV _553_ (
    .A(_294_),
    .B(_296_),
    .Y(_181_)
  );
  ANX1_CV _554_ (
    .A(_231_),
    .B(_294_),
    .Y(_297_)
  );
  ORX1_CV _555_ (
    .A(_231_),
    .B(_294_),
    .Y(_298_)
  );
  NDX1_CV _556_ (
    .A(_440_),
    .B(_298_),
    .Y(_299_)
  );
  NRX1_CV _557_ (
    .A(_297_),
    .B(_299_),
    .Y(_182_)
  );
  ANX1_CV _558_ (
    .A(_232_),
    .B(_297_),
    .Y(_300_)
  );
  ORX1_CV _559_ (
    .A(_232_),
    .B(_297_),
    .Y(_301_)
  );
  NDX1_CV _560_ (
    .A(_440_),
    .B(_301_),
    .Y(_302_)
  );
  NRX1_CV _561_ (
    .A(_300_),
    .B(_302_),
    .Y(_183_)
  );
  ANX1_CV _562_ (
    .A(_233_),
    .B(_300_),
    .Y(_303_)
  );
  ORX1_CV _563_ (
    .A(_233_),
    .B(_300_),
    .Y(_304_)
  );
  NDX1_CV _564_ (
    .A(_440_),
    .B(_304_),
    .Y(_305_)
  );
  NRX1_CV _565_ (
    .A(_303_),
    .B(_305_),
    .Y(_184_)
  );
  ANX1_CV _566_ (
    .A(_234_),
    .B(_303_),
    .Y(_306_)
  );
  ORX1_CV _567_ (
    .A(_234_),
    .B(_303_),
    .Y(_307_)
  );
  NDX1_CV _568_ (
    .A(_440_),
    .B(_307_),
    .Y(_308_)
  );
  NRX1_CV _569_ (
    .A(_306_),
    .B(_308_),
    .Y(_185_)
  );
  ANX1_CV _570_ (
    .A(_235_),
    .B(_306_),
    .Y(_309_)
  );
  ORX1_CV _571_ (
    .A(_235_),
    .B(_306_),
    .Y(_310_)
  );
  NDX1_CV _572_ (
    .A(_440_),
    .B(_310_),
    .Y(_311_)
  );
  NRX1_CV _573_ (
    .A(_309_),
    .B(_311_),
    .Y(_186_)
  );
  ANX1_CV _574_ (
    .A(_236_),
    .B(_309_),
    .Y(_312_)
  );
  ORX1_CV _575_ (
    .A(_236_),
    .B(_309_),
    .Y(_313_)
  );
  NDX1_CV _576_ (
    .A(_440_),
    .B(_313_),
    .Y(_314_)
  );
  NRX1_CV _577_ (
    .A(_312_),
    .B(_314_),
    .Y(_187_)
  );
  ANX1_CV _578_ (
    .A(_237_),
    .B(_312_),
    .Y(_315_)
  );
  ORX1_CV _579_ (
    .A(_237_),
    .B(_312_),
    .Y(_316_)
  );
  NDX1_CV _580_ (
    .A(_440_),
    .B(_316_),
    .Y(_317_)
  );
  NRX1_CV _581_ (
    .A(_315_),
    .B(_317_),
    .Y(_188_)
  );
  ANX1_CV _582_ (
    .A(_239_),
    .B(_315_),
    .Y(_318_)
  );
  ORX1_CV _583_ (
    .A(_239_),
    .B(_315_),
    .Y(_319_)
  );
  NDX1_CV _584_ (
    .A(_440_),
    .B(_319_),
    .Y(_320_)
  );
  NRX1_CV _585_ (
    .A(_318_),
    .B(_320_),
    .Y(_190_)
  );
  ANX1_CV _586_ (
    .A(_240_),
    .B(_318_),
    .Y(_321_)
  );
  ORX1_CV _587_ (
    .A(_240_),
    .B(_318_),
    .Y(_322_)
  );
  NDX1_CV _588_ (
    .A(_440_),
    .B(_322_),
    .Y(_323_)
  );
  NRX1_CV _589_ (
    .A(_321_),
    .B(_323_),
    .Y(_191_)
  );
  ANX1_CV _590_ (
    .A(_241_),
    .B(_321_),
    .Y(_324_)
  );
  ORX1_CV _591_ (
    .A(_241_),
    .B(_321_),
    .Y(_325_)
  );
  NDX1_CV _592_ (
    .A(_440_),
    .B(_325_),
    .Y(_326_)
  );
  NRX1_CV _593_ (
    .A(_324_),
    .B(_326_),
    .Y(_192_)
  );
  ANX1_CV _594_ (
    .A(_242_),
    .B(_324_),
    .Y(_327_)
  );
  ORX1_CV _595_ (
    .A(_242_),
    .B(_324_),
    .Y(_328_)
  );
  NDX1_CV _596_ (
    .A(_440_),
    .B(_328_),
    .Y(_329_)
  );
  NRX1_CV _597_ (
    .A(_327_),
    .B(_329_),
    .Y(_193_)
  );
  ANX1_CV _598_ (
    .A(_243_),
    .B(_327_),
    .Y(_330_)
  );
  ORX1_CV _599_ (
    .A(_243_),
    .B(_327_),
    .Y(_331_)
  );
  NDX1_CV _600_ (
    .A(_440_),
    .B(_331_),
    .Y(_332_)
  );
  NRX1_CV _601_ (
    .A(_330_),
    .B(_332_),
    .Y(_194_)
  );
  ANX1_CV _602_ (
    .A(_244_),
    .B(_330_),
    .Y(_333_)
  );
  ORX1_CV _603_ (
    .A(_244_),
    .B(_330_),
    .Y(_334_)
  );
  NDX1_CV _604_ (
    .A(_440_),
    .B(_334_),
    .Y(_335_)
  );
  NRX1_CV _605_ (
    .A(_333_),
    .B(_335_),
    .Y(_195_)
  );
  ANX1_CV _606_ (
    .A(_245_),
    .B(_333_),
    .Y(_336_)
  );
  ORX1_CV _607_ (
    .A(_245_),
    .B(_333_),
    .Y(_337_)
  );
  NDX1_CV _608_ (
    .A(_440_),
    .B(_337_),
    .Y(_338_)
  );
  NRX1_CV _609_ (
    .A(_336_),
    .B(_338_),
    .Y(_196_)
  );
  ANX1_CV _610_ (
    .A(_246_),
    .B(_336_),
    .Y(_339_)
  );
  ORX1_CV _611_ (
    .A(_246_),
    .B(_336_),
    .Y(_340_)
  );
  NDX1_CV _612_ (
    .A(_440_),
    .B(_340_),
    .Y(_341_)
  );
  NRX1_CV _613_ (
    .A(_339_),
    .B(_341_),
    .Y(_197_)
  );
  ANX1_CV _614_ (
    .A(_247_),
    .B(_339_),
    .Y(_342_)
  );
  ORX1_CV _615_ (
    .A(_247_),
    .B(_339_),
    .Y(_343_)
  );
  NDX1_CV _616_ (
    .A(_440_),
    .B(_343_),
    .Y(_344_)
  );
  NRX1_CV _617_ (
    .A(_342_),
    .B(_344_),
    .Y(_198_)
  );
  ANX1_CV _618_ (
    .A(_248_),
    .B(_342_),
    .Y(_345_)
  );
  ORX1_CV _619_ (
    .A(_248_),
    .B(_342_),
    .Y(_346_)
  );
  NDX1_CV _620_ (
    .A(_440_),
    .B(_346_),
    .Y(_347_)
  );
  NRX1_CV _621_ (
    .A(_345_),
    .B(_347_),
    .Y(_199_)
  );
  NDX1_CV _622_ (
    .A(_250_),
    .B(_345_),
    .Y(_348_)
  );
  ORX1_CV _623_ (
    .A(_250_),
    .B(_345_),
    .Y(_349_)
  );
  ANX1_CV _624_ (
    .A(_440_),
    .B(_349_),
    .Y(_350_)
  );
  ANX1_CV _625_ (
    .A(_348_),
    .B(_350_),
    .Y(_201_)
  );
  ENX1_CV _626_ (
    .A(_251_),
    .B(_348_),
    .Y(_351_)
  );
  ANX1_CV _627_ (
    .A(_440_),
    .B(_351_),
    .Y(_202_)
  );
  ANX1_CV _628_ (
    .A(_446_),
    .B(_221_),
    .Y(_352_)
  );
  NDX1_CV _629_ (
    .A(_436_),
    .B(_352_),
    .Y(_353_)
  );
  NRX1_CV _630_ (
    .A(_230_),
    .B(_231_),
    .Y(_354_)
  );
  NRX1_CV _631_ (
    .A(_232_),
    .B(_233_),
    .Y(_355_)
  );
  ANX1_CV _632_ (
    .A(_354_),
    .B(_355_),
    .Y(_356_)
  );
  NRX1_CV _633_ (
    .A(_257_),
    .B(_258_),
    .Y(_357_)
  );
  NRX1_CV _634_ (
    .A(_228_),
    .B(_229_),
    .Y(_358_)
  );
  ANX1_CV _635_ (
    .A(_357_),
    .B(_358_),
    .Y(_359_)
  );
  ANX1_CV _636_ (
    .A(_356_),
    .B(_359_),
    .Y(_360_)
  );
  NRX1_CV _637_ (
    .A(_240_),
    .B(_241_),
    .Y(_361_)
  );
  NRX1_CV _638_ (
    .A(_239_),
    .B(_242_),
    .Y(_362_)
  );
  ANX1_CV _639_ (
    .A(_361_),
    .B(_362_),
    .Y(_363_)
  );
  NRX1_CV _640_ (
    .A(_234_),
    .B(_235_),
    .Y(_364_)
  );
  NRX1_CV _641_ (
    .A(_236_),
    .B(_237_),
    .Y(_365_)
  );
  ANX1_CV _642_ (
    .A(_364_),
    .B(_365_),
    .Y(_366_)
  );
  ANX1_CV _643_ (
    .A(_363_),
    .B(_366_),
    .Y(_367_)
  );
  NRX1_CV _644_ (
    .A(_247_),
    .B(_248_),
    .Y(_368_)
  );
  NRX1_CV _645_ (
    .A(_250_),
    .B(_251_),
    .Y(_369_)
  );
  ANX1_CV _646_ (
    .A(_368_),
    .B(_369_),
    .Y(_370_)
  );
  NRX1_CV _647_ (
    .A(_243_),
    .B(_244_),
    .Y(_371_)
  );
  NRX1_CV _648_ (
    .A(_245_),
    .B(_246_),
    .Y(_372_)
  );
  ANX1_CV _649_ (
    .A(_371_),
    .B(_372_),
    .Y(_373_)
  );
  ANX1_CV _650_ (
    .A(_370_),
    .B(_373_),
    .Y(_374_)
  );
  ANX1_CV _651_ (
    .A(_367_),
    .B(_374_),
    .Y(_375_)
  );
  ANX1_CV _652_ (
    .A(_360_),
    .B(_375_),
    .Y(_376_)
  );
  ANX1_CV _653_ (
    .A(_279_),
    .B(_376_),
    .Y(_377_)
  );
  NDX1_CV _654_ (
    .A(_445_),
    .B(_221_),
    .Y(_378_)
  );
  ORX1_CV _655_ (
    .A(_446_),
    .B(_378_),
    .Y(_379_)
  );
  ORX1_CV _656_ (
    .A(_377_),
    .B(_379_),
    .Y(_380_)
  );
  NDX1_CV _657_ (
    .A(_353_),
    .B(_380_),
    .Y(_381_)
  );
  ORX1_CV _658_ (
    .A(_441_),
    .B(_377_),
    .Y(_382_)
  );
  NDX1_CV _659_ (
    .A(_381_),
    .B(_382_),
    .Y(_383_)
  );
  NDX1_CV _660_ (
    .A(_437_),
    .B(_441_),
    .Y(_384_)
  );
  NDX1_CV _661_ (
    .A(_221_),
    .B(_438_),
    .Y(_385_)
  );
  ANX1_CV _662_ (
    .A(_445_),
    .B(_352_),
    .Y(_386_)
  );
  NDX1_CV _663_ (
    .A(_445_),
    .B(_352_),
    .Y(_387_)
  );
  NRX1_CV _664_ (
    .A(_253_),
    .B(_254_),
    .Y(_388_)
  );
  NRX1_CV _665_ (
    .A(_255_),
    .B(_256_),
    .Y(_389_)
  );
  ANX1_CV _666_ (
    .A(_388_),
    .B(_389_),
    .Y(_390_)
  );
  ANX1_CV _667_ (
    .A(_249_),
    .B(_435_),
    .Y(_391_)
  );
  ANX1_CV _668_ (
    .A(_261_),
    .B(_391_),
    .Y(_392_)
  );
  ANX1_CV _669_ (
    .A(_390_),
    .B(_392_),
    .Y(_393_)
  );
  NDX1_CV _670_ (
    .A(_376_),
    .B(_393_),
    .Y(_394_)
  );
  NDX1_CV _671_ (
    .A(_386_),
    .B(_394_),
    .Y(_395_)
  );
  NDX1_CV _672_ (
    .A(_385_),
    .B(_395_),
    .Y(_396_)
  );
  NDX1_CV _673_ (
    .A(_222_),
    .B(_394_),
    .Y(_397_)
  );
  NDX1_CV _674_ (
    .A(_396_),
    .B(_397_),
    .Y(_398_)
  );
  ANX1_CV _675_ (
    .A(_384_),
    .B(_398_),
    .Y(_399_)
  );
  NDX1_CV _676_ (
    .A(_383_),
    .B(_399_),
    .Y(_212_)
  );
  ANX1_CV _677_ (
    .A(_353_),
    .B(_379_),
    .Y(_400_)
  );
  IVX1_CV _678_ (
    .A(_400_),
    .Y(_401_)
  );
  NDX1_CV _679_ (
    .A(_377_),
    .B(_401_),
    .Y(_402_)
  );
  NDX1_CV _680_ (
    .A(_385_),
    .B(_387_),
    .Y(_403_)
  );
  NDX1_CV _681_ (
    .A(_394_),
    .B(_403_),
    .Y(_404_)
  );
  ANX1_CV _682_ (
    .A(_221_),
    .B(_404_),
    .Y(_405_)
  );
  NDX1_CV _683_ (
    .A(_400_),
    .B(_405_),
    .Y(_406_)
  );
  NDX1_CV _684_ (
    .A(_442_),
    .B(_406_),
    .Y(_407_)
  );
  NDX1_CV _685_ (
    .A(_402_),
    .B(_407_),
    .Y(_213_)
  );
  ORX1_CV _686_ (
    .A(_377_),
    .B(_400_),
    .Y(_408_)
  );
  NDX1_CV _687_ (
    .A(_405_),
    .B(_408_),
    .Y(_409_)
  );
  ORX1_CV _688_ (
    .A(_353_),
    .B(_377_),
    .Y(_410_)
  );
  ANX1_CV _689_ (
    .A(_443_),
    .B(_409_),
    .Y(_214_)
  );
  ANX1_CV _690_ (
    .A(_220_),
    .B(_219_),
    .Y(_411_)
  );
  NRX1_CV _691_ (
    .A(_221_),
    .B(_411_),
    .Y(_412_)
  );
  ORX1_CV _692_ (
    .A(_221_),
    .B(_411_),
    .Y(_413_)
  );
  NDX1_CV _693_ (
    .A(_436_),
    .B(_412_),
    .Y(_414_)
  );
  NDX1_CV _694_ (
    .A(_441_),
    .B(_439_),
    .Y(_415_)
  );
  ANX1_CV _695_ (
    .A(_395_),
    .B(_413_),
    .Y(_416_)
  );
  ANX1_CV _696_ (
    .A(_415_),
    .B(_416_),
    .Y(_417_)
  );
  NDX1_CV _697_ (
    .A(_380_),
    .B(_417_),
    .Y(_418_)
  );
  ANX1_CV _698_ (
    .A(_414_),
    .B(_418_),
    .Y(_216_)
  );
  ORX1_CV _699_ (
    .A(_446_),
    .B(_413_),
    .Y(_419_)
  );
  NDX1_CV _700_ (
    .A(_442_),
    .B(_439_),
    .Y(_420_)
  );
  ANX1_CV _701_ (
    .A(_416_),
    .B(_420_),
    .Y(_421_)
  );
  NDX1_CV _702_ (
    .A(_410_),
    .B(_421_),
    .Y(_422_)
  );
  ANX1_CV _703_ (
    .A(_419_),
    .B(_422_),
    .Y(_217_)
  );
  NDX1_CV _704_ (
    .A(_433_),
    .B(_412_),
    .Y(_423_)
  );
  NDX1_CV _705_ (
    .A(_433_),
    .B(_394_),
    .Y(_424_)
  );
  NDX1_CV _706_ (
    .A(_403_),
    .B(_424_),
    .Y(_425_)
  );
  NDX1_CV _707_ (
    .A(_443_),
    .B(_439_),
    .Y(_426_)
  );
  ANX1_CV _708_ (
    .A(_413_),
    .B(_426_),
    .Y(_427_)
  );
  ANX1_CV _709_ (
    .A(_425_),
    .B(_427_),
    .Y(_428_)
  );
  NDX1_CV _710_ (
    .A(_402_),
    .B(_428_),
    .Y(_429_)
  );
  ANX1_CV _711_ (
    .A(_423_),
    .B(_429_),
    .Y(_218_)
  );
  NDX1_CV _712_ (
    .A(_260_),
    .B(_412_),
    .Y(_430_)
  );
  NDX1_CV _713_ (
    .A(_379_),
    .B(_430_),
    .Y(_211_)
  );
  NDX1_CV _714_ (
    .A(_259_),
    .B(_412_),
    .Y(_431_)
  );
  NDX1_CV _715_ (
    .A(_385_),
    .B(_431_),
    .Y(_210_)
  );
  NDX1_CV _716_ (
    .A(_444_),
    .B(_412_),
    .Y(_432_)
  );
  NDX1_CV _717_ (
    .A(_387_),
    .B(_432_),
    .Y(_215_)
  );
  IVX1_CV _718_ (
    .A(_226_),
    .Y(_224_)
  );
  IVX1_CV _719_ (
    .A(_226_),
    .Y(_225_)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _720_ (
    .CK(_493_),
    .D(_004_),
    .Q(read),
    .QN(_448_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _721_ (
    .CK(_494_),
    .D(_001_),
    .Q(erase),
    .QN(_449_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:61" *)
  DFSRQNX1_CV _722_ (
    .CK(_495_),
    .D(_002_),
    .Q(expose),
    .QN(_450_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _723_ (
    .CK(clk),
    .D(_005_[0]),
    .Q(state[0]),
    .QN(_451_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _724_ (
    .CK(clk),
    .D(_005_[1]),
    .Q(state[1]),
    .QN(_452_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _725_ (
    .CK(clk),
    .D(_005_[2]),
    .Q(state[2]),
    .QN(_453_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _726_ (
    .CK(clk),
    .D(_003_[0]),
    .Q(next_state[0]),
    .QN(_454_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _727_ (
    .CK(clk),
    .D(_003_[1]),
    .Q(next_state[1]),
    .QN(_455_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _728_ (
    .CK(clk),
    .D(_003_[2]),
    .Q(next_state[2]),
    .QN(_456_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _729_ (
    .CK(clk),
    .D(_000_[0]),
    .Q(counter[0]),
    .QN(_457_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _730_ (
    .CK(clk),
    .D(_000_[1]),
    .Q(counter[1]),
    .QN(_458_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _731_ (
    .CK(clk),
    .D(_000_[2]),
    .Q(counter[2]),
    .QN(_459_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _732_ (
    .CK(clk),
    .D(_000_[3]),
    .Q(counter[3]),
    .QN(_460_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _733_ (
    .CK(clk),
    .D(_000_[4]),
    .Q(counter[4]),
    .QN(_461_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _734_ (
    .CK(clk),
    .D(_000_[5]),
    .Q(counter[5]),
    .QN(_462_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _735_ (
    .CK(clk),
    .D(_000_[6]),
    .Q(counter[6]),
    .QN(_463_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _736_ (
    .CK(clk),
    .D(_000_[7]),
    .Q(counter[7]),
    .QN(_464_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _737_ (
    .CK(clk),
    .D(_000_[8]),
    .Q(counter[8]),
    .QN(_465_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _738_ (
    .CK(clk),
    .D(_000_[9]),
    .Q(counter[9]),
    .QN(_466_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _739_ (
    .CK(clk),
    .D(_000_[10]),
    .Q(counter[10]),
    .QN(_467_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _740_ (
    .CK(clk),
    .D(_000_[11]),
    .Q(counter[11]),
    .QN(_468_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _741_ (
    .CK(clk),
    .D(_000_[12]),
    .Q(counter[12]),
    .QN(_469_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _742_ (
    .CK(clk),
    .D(_000_[13]),
    .Q(counter[13]),
    .QN(_470_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _743_ (
    .CK(clk),
    .D(_000_[14]),
    .Q(counter[14]),
    .QN(_471_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _744_ (
    .CK(clk),
    .D(_000_[15]),
    .Q(counter[15]),
    .QN(_472_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _745_ (
    .CK(clk),
    .D(_000_[16]),
    .Q(counter[16]),
    .QN(_473_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _746_ (
    .CK(clk),
    .D(_000_[17]),
    .Q(counter[17]),
    .QN(_474_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _747_ (
    .CK(clk),
    .D(_000_[18]),
    .Q(counter[18]),
    .QN(_475_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _748_ (
    .CK(clk),
    .D(_000_[19]),
    .Q(counter[19]),
    .QN(_476_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _749_ (
    .CK(clk),
    .D(_000_[20]),
    .Q(counter[20]),
    .QN(_477_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _750_ (
    .CK(clk),
    .D(_000_[21]),
    .Q(counter[21]),
    .QN(_478_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _751_ (
    .CK(clk),
    .D(_000_[22]),
    .Q(counter[22]),
    .QN(_479_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _752_ (
    .CK(clk),
    .D(_000_[23]),
    .Q(counter[23]),
    .QN(_480_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _753_ (
    .CK(clk),
    .D(_000_[24]),
    .Q(counter[24]),
    .QN(_481_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _754_ (
    .CK(clk),
    .D(_000_[25]),
    .Q(counter[25]),
    .QN(_482_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _755_ (
    .CK(clk),
    .D(_000_[26]),
    .Q(counter[26]),
    .QN(_483_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _756_ (
    .CK(clk),
    .D(_000_[27]),
    .Q(counter[27]),
    .QN(_484_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _757_ (
    .CK(clk),
    .D(_000_[28]),
    .Q(counter[28]),
    .QN(_485_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _758_ (
    .CK(clk),
    .D(_000_[29]),
    .Q(counter[29]),
    .QN(_486_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _759_ (
    .CK(clk),
    .D(_000_[30]),
    .Q(counter[30]),
    .QN(_487_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:102" *)
  DFSRQNX1_CV _760_ (
    .CK(clk),
    .D(_000_[31]),
    .Q(counter[31]),
    .QN(_488_),
    .R(reset),
    .S(1'h0)
  );
  assign convert = 1'h0;
  assign _149_ = _451_;
  assign _150_ = _452_;
  assign _084_ = _453_;
  assign _096_ = _454_;
  assign _447_ = state[2];
  assign _227_ = counter[0];
  assign _000_[0] = _178_;
  assign _238_ = counter[1];
  assign _000_[1] = _189_;
  assign _249_ = counter[2];
  assign _000_[2] = _200_;
  assign _252_ = counter[3];
  assign _000_[3] = _203_;
  assign _253_ = counter[4];
  assign _000_[4] = _204_;
  assign _254_ = counter[5];
  assign _000_[5] = _205_;
  assign _255_ = counter[6];
  assign _000_[6] = _206_;
  assign _256_ = counter[7];
  assign _000_[7] = _207_;
  assign _257_ = counter[8];
  assign _000_[8] = _208_;
  assign _258_ = counter[9];
  assign _000_[9] = _209_;
  assign _228_ = counter[10];
  assign _000_[10] = _179_;
  assign _229_ = counter[11];
  assign _000_[11] = _180_;
  assign _230_ = counter[12];
  assign _000_[12] = _181_;
  assign _231_ = counter[13];
  assign _000_[13] = _182_;
  assign _232_ = counter[14];
  assign _000_[14] = _183_;
  assign _233_ = counter[15];
  assign _000_[15] = _184_;
  assign _234_ = counter[16];
  assign _000_[16] = _185_;
  assign _235_ = counter[17];
  assign _000_[17] = _186_;
  assign _236_ = counter[18];
  assign _000_[18] = _187_;
  assign _237_ = counter[19];
  assign _000_[19] = _188_;
  assign _239_ = counter[20];
  assign _000_[20] = _190_;
  assign _240_ = counter[21];
  assign _000_[21] = _191_;
  assign _241_ = counter[22];
  assign _000_[22] = _192_;
  assign _242_ = counter[23];
  assign _000_[23] = _193_;
  assign _243_ = counter[24];
  assign _000_[24] = _194_;
  assign _244_ = counter[25];
  assign _000_[25] = _195_;
  assign _245_ = counter[26];
  assign _000_[26] = _196_;
  assign _246_ = counter[27];
  assign _000_[27] = _197_;
  assign _247_ = counter[28];
  assign _000_[28] = _198_;
  assign _248_ = counter[29];
  assign _000_[29] = _199_;
  assign _250_ = counter[30];
  assign _000_[30] = _201_;
  assign _251_ = counter[31];
  assign _000_[31] = _202_;
  assign _446_ = state[1];
  assign _445_ = state[0];
  assign _221_ = _453_;
  assign _441_ = next_state[0];
  assign _222_ = _454_;
  assign _003_[0] = _212_;
  assign _442_ = next_state[1];
  assign _003_[1] = _213_;
  assign _443_ = next_state[2];
  assign _003_[2] = _214_;
  assign _220_ = _452_;
  assign _219_ = _451_;
  assign _005_[0] = _216_;
  assign _005_[1] = _217_;
  assign _005_[2] = _218_;
  assign _260_ = expose;
  assign _002_ = _211_;
  assign _259_ = erase;
  assign _001_ = _210_;
  assign _444_ = read;
  assign _004_ = _215_;
  assign _226_ = clk;
  assign _493_ = _223_;
  assign _494_ = _224_;
  assign _495_ = _225_;
endmodule
